json-print/jasonkuhrt
neongreen/haskell-ex pull request #28
Opened 2016-10-03 18:51 UTC by jasonkuhrt

2016-10-08 19:14 UTC, neongreen requested changes

2016-10-08 19:14 UTC, neongreen commented on week4/json-print/jasonkuhrt/Main.hs
> +  . List.map stringify
Any specific reason why `map` is qualified but e.g. `++` isn't? I'm asking 'cause `map` is usually used unqualified, but maybe you have a good reason for it (or maybe it just looks nicer to you – it doesn't to me but that's just because I'm used to unqualified `map`).

2016-10-08 19:14 UTC, neongreen commented on week4/json-print/jasonkuhrt/Main.hs
> +    | mod' n 1 == 0 = (takeWhile (/= '.') . show) n
You could've used `properFraction` instead.

2016-10-08 19:14 UTC, neongreen commented on week4/json-print/jasonkuhrt/Main.hs
> +  . escape '\\' -- Otherwise parse yields invalid/different strings. [1]
This doesn't escape control characters like `'\1'` as JSON spec requires. Also, I think you could've instead written something like

```haskell
escape :: [Char] -> String -> String
escape cEscapes s =
  (\ c -> if c `elem` cEscapes then ['\\', '\\', c] else [c]) =<< s
```

to do escaping in one pass by writing `escape ['\\', '\"']`. Anyway, it won't work with control characters or newlines so it doesn't matter.

2016-10-08 19:14 UTC, neongreen commented on week4/json-print/jasonkuhrt/Main.hs
> +  stringifyKeyValue k v = wrapQuotes k ++ ":" ++ stringify v
This doesn't escape key values.

2016-10-08 20:08 UTC, jasonkuhrt commented on week4/json-print/jasonkuhrt/Main.hs
> +  . List.map stringify
Weird slip on my part. I usually always use `fmap`. Will fix.

2016-10-08 21:00 UTC, jasonkuhrt commented on week4/json-print/jasonkuhrt/Main.hs
> +    | mod' n 1 == 0 = (takeWhile (/= '.') . show) n
Saves me an `import` too.

2016-10-09 13:32 UTC, jasonkuhrt commented on week4/json-print/jasonkuhrt/Main.hs
> +  . escape '\\' -- Otherwise parse yields invalid/different strings. [1]
Makes sense. The revised solution changes all this anyways since as you said this was failing to escape control characters.

2016-10-09 13:32 UTC, jasonkuhrt commented
@neongreen I think this is better now.

2016-10-09 15:44 UTC, neongreen commented
It's still not quite right.

```
> putStrLn . stringify $ S "\""
"\\""
```
 
The right answer would've been `"\""`.

2016-10-09 22:23 UTC, jasonkuhrt commented
But why not, since that's the source string? E.g.:

```js
> JSON.stringify("\"")
'"\\""'
```

2016-10-09 22:30 UTC, neongreen commented
`"\""` is a string with a single character inside – a quote. Verbatim it's `"`.

In JSON, such a string looks like – verbatim – `"\""`:

```
[yom@shiny ~]$ jsc
>>> print("\"")
"
```

`putStrLn` prints a string verbatim. Therefore, when I `putStrLn` the JSON representation of a string with a single quote in it, I expect `"\""` to be printed. If I `show`-ed it instead, I'd get `"\"\\\"\""`.

`"\\""` isn't even a valid string literal:

```
[yom@shiny ~]$ jsc
>>> "\\""
Exception: SyntaxError: Unexpected EOF
```

2016-10-09 22:31 UTC, jasonkuhrt commented
I was about to edit with "nevermind" heh:

```js
> console.log(JSON.stringify("\""))
"\""
```

2016-10-10 01:43 UTC, jasonkuhrt commented
Fixed:

```
❯   putStrLn $ stringify $ S "\""
"\""
```

2016-10-10 10:55 UTC, neongreen commented
Same for slashes:

```
> putStrLn . stringify $ S "\\"
"\\\\"
```

(The right answer is `"\\"`.)

Also, control characters:

```
> putStrLn . stringify $ S "\1"
"\\u0001"

> putStrLn . stringify $ S "\n"
"\\n"
```

The right answers are `"\u0001"` and `"\n"`.

2016-10-11 18:15 UTC, merged