Spiral/aneksteind
neongreen/haskell-ex pull request #9
Opened 2016-09-22 13:48 UTC by aneksteind

2016-09-24 20:07 UTC, balachandranc commented on week4/spiral/spiral.hs
> +    i <- getInt
You can avoid writing "getInt" function. You could do:
`i <- read <$> getLine`
The compiler will infer the type of `read` by how the value is used down the line.

2016-09-24 20:16 UTC, balachandranc reviewed
Minor comments.

2016-09-24 20:18 UTC, aneksteind commented on week4/spiral/spiral.hs
> +    i <- getInt
ah interesting @balachandranc, thank you

2016-09-26 11:15 UTC, 444c43 commented
using Data.Matrix is a pretty interesting approach. i didn't even know this library existed.

odd number sizes seem to look better than even as the inside ends up as a grouping of 2x2 stars. for instance, spiral 4 looks like:

```
* * * * 
      * 
* *   * 
* * * * 
```
by adding an additional row to your matrix. i'm not sure the `Direction = R | D | U | L` approach would work so cleanly though.

regardless, i tried it out and it works!

2016-09-26 11:16 UTC, 444c43 approved these changes

2016-09-26 11:21 UTC, int-index commented on week4/spiral/spiral.hs
> +    i <- getInt
`read <$> getLine` is called `readLn`:

```
Prelude> :t readLn 
readLn :: Read a => IO a
```

2016-10-01 22:16 UTC, neongreen requested changes
It could've been done quite a bit easier – see @vitcra's and @balachandranc's solutions. Also, put the spiral.hs file into a directory called `aneksteind` before merging.

2016-10-01 22:16 UTC, neongreen commented on week4/spiral/spiral.hs
> +    putStrLn("Please enter a size for the spiral!")
Unnecessary parens

2016-10-01 22:16 UTC, neongreen commented on week4/spiral/spiral.hs
> +buildSpiral m i dir curr count | count >=3 = (setElem 1 curr m)
Unnecessary parens

2016-10-01 22:16 UTC, neongreen commented on week4/spiral/spiral.hs
> +                               | (available m curr) =
Unnecessary parens

2016-10-01 22:16 UTC, neongreen commented on week4/spiral/spiral.hs
> +    if (atBound dir curr i m)
Unnecessary parens

2016-10-01 22:16 UTC, neongreen commented on week4/spiral/spiral.hs
> +available m pos = if (m ! pos) == 1 then False else True
`available m pos = m ! pos /= 1`

2016-10-01 22:16 UTC, neongreen commented
(To be clear, only “put the spiral.hs file into a directory called aneksteind before merging” is a requested change.)

2016-10-01 22:55 UTC, merged